### ISSUE TITLE
Whether all list types can output

### ISSUE THREAD

**Issue by DanielTian90** [OSU-Haolin/Road-Detection-and-Vehicle-Control#4]
Hi,
I am learning Lidar classification, in README file it shows support below type:
0---pedestrian / 1---car / 2---bus / 3---non-motorized vehicle / 4---motorcycle /
5---bicycle / 6---truck / 7---work van / 8---animal / 9---background /
I want to know whether all these types can output in some interface, and did you test the accuracy of the output?
BR,
Daniel

**Comment by OSU-Haolin** [comment]
I think the question you asked is about my another repo(ResNet), right?

**Comment by DanielTian90** [comment]
So in this repostory there is no classification type like car/pedestrian/bicycle etc. output, right?
And in ResNet respo did you provide classification type output?

**Comment by OSU-Haolin** [comment]
> So in this repostory there is no classification type like car/pedestrian/bicycle etc. output, right?
> And in ResNet respo did you provide classification type output?

You are right. This repo is about road segmentation. And in ResNet, the program outputs 10 classes as you said.
